### ISSUE TITLE
[Feature Request] Make airsonic-advanced compatible with Symfonium

### ISSUE THREAD

**Issue by awsms** [kagemomiji/airsonic-advanced#129]
### Scope

GUI

### What problem

Symfonium is a closed-source android client for subsonic servers.
To get it working, you have to enable the legacy mode on the app to be compatible with airsonic-advanced, and that makes the whole scanning process extremely slow.
It's a rather popular client for airsonic so I assumed you would be interested in this.

### Feature

More reading here: https://support.symfonium.app/t/wiki-subsonic-media-provider-configuration/160

**Comment by awsms** [comment]
Related: https://github.com/airsonic-advanced/airsonic-advanced/issues/885

**Comment by jeffgt14** [comment]
I see this is supposedly resolved but running Edge Release 11.1.3-SNAPSHOT.20231203152933 I still cannot get Symfonium to scan any media. It goes scans all of my artists and albums but songs remain at "0" and no media is shown. I'm not sure if that was the bug here or if this is a separate bug.

**Comment by awsms** [comment]
> It goes scans all of my artists and albums but songs remain at "0" and no media is shown.

Mh I've always been having this issue. When asked on the symfonium forums, the dev told me it was on my side as it was working for him.
