### ISSUE TITLE
[Bug] NullPointerException on search querries

### ISSUE THREAD

**Issue by awsms** [kagemomiji/airsonic-advanced#131]
### What happened?

(i actually always had this bug on airsonic but never mentionned since previous forks are abandonnware)

searching for a song/artist etc will sometimes fail with a NullPointerException exception on android clients.
this happens on random search querries. but once a querry triggers the api error, it's the case on all the mobile clients.
tried with ultrasonic/dsub

### Steps to reproduce

1. Search for a song, album, artist or whatever in an android client
2. Query will sometimes fail, with a "NullPointerException" error

### Version

11.0.2 (Stable)

### Operating System

linux

### Java Version

openjdk version "17.0.5" 2022-10-18

### Database

Other

### DB Detail

postgres 14.6

### Configuration paramter

# Airsonic preferences.  NOTE: This file is automatically generated. Do not modify while application is running

JWTKey=xxxxx
SettingsChanged=1677532867214
EncryptionKeyPassword=xxxx
EncryptionKeySalt=xxxx
spring.liquibase.parameters.mysqlVarcharLimit=384
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=xxxx
spring.datasource.url=jdbc:postgresql://localhost:5432/airsonic?stringtype=unspecified
spring.datasource.username=airsonic
DbBackupUpdateInterval=-1
DbBackupRetentionCount=2
IndexCreationInterval=1
IndexCreationHour=3
FastCacheEnabled=false
OrganizeByFolderStructure=true
UploadsFolder=%{['USER_MUSIC_FOLDERS'][0]}/Incoming
ExcludePattern=
IgnoreSymLinks=false
HideIndexedFiles=true
SplitOptions=-ss %o -t %d
SplitCommand=ffmpeg %S -i %s -vcodec copy -acodec copy -f %f -
DownsamplingCommand4=ffmpeg %S -i %s -map 0:0 -b:a %bk -v 0 -f mp3 -
HlsCommand4=ffmpeg -ss %o -i %s -s %wx%h -async 1 -c:v libx264 -flags +cgop -b:v %vk -maxrate %bk -preset superfast -copyts -b:a %rk -bufsize 256k -map 0:0 -map 0:%i -ac 2 -ar 44100 -v 0 -threads 0 -force_key_frames expr:gte(t,n_forced*10) -start_number %j -hls_time %d -hls_list_size 0 -hls_segment_filename %n %p
JukeboxCommand2=ffmpeg -ss %o -i %s -map 0:0 -v 0 -ar 44100 -ac 2 -f s16be -
VideoImageCommand=ffmpeg -r 1 -ss %o -t 1 -i %s -s %wx%h -v 0 -f mjpeg -
SubtitlesExtractionCommand=ffmpeg -i %s -map 0:%i -f %f -
TranscodeEstimateTimePadding=2000
TranscodeEstimateBytePadding=0

### language

None

### Relevant log output

```console
Feb 28 20:12:54 java[1315238]: 2023-02-28 20:12:54.359 ERROR --- o.a.p.s.LoggingExceptionResolver         : 127.0.0.1: An exception occurred while loading http://mysuperserv.er/rest/search2.view?query=Eddy%20%26%20Larry%20Hot%20Step%20Jump&artistCount=10&albumCount=25&songCount=50&c=Ultrasonic&f=json&v=1.15.0&p=<hidden>&u=<hidden>
Feb 28 20:12:54 java[1315238]: java.lang.NullPointerException: null
Feb 28 20:12:54 java[1315238]: 2023-02-28 20:12:54.359  WARN --- o.a.player.filter.RESTFilter             : Error in REST API
Feb 28 20:12:54 java[1315238]: java.lang.NullPointerException: null
```

**Comment by awsms** [comment]
Looks like enabling Fast access mode in the settings partially fixed it!

**Comment by c-x-r** [comment]
I encountered this bug too. It only happened with 1 search term, so I wasn't able to find a pattern.
I'm using mariadb 10.5, and had switched from https://github.com/airsonic-advanced/airsonic-advanced.
Enabling fast access mode didn't fix it, but dropping the database and creating a new one did.

**Comment by kagemomiji** [comment]
@awsms @c-x-r 
I have tried to reproduce this error, but I have not succeeded. 
I want airsonic.log when this error occurs. Do you have it?
