### ISSUE TITLE
[Bug]: version of the Java Runtime

### ISSUE THREAD

**Issue by microniko** [kagemomiji/airsonic-advanced#139]
### What happened?

I would like test this repo version of Airsonic. With the 11.0.2 version, I had this error :

```
java[191030]: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/airsonic/player/Application has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

```
# java --version
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Debian-1deb11u1, mixed mode, sharing)
```

### Steps to reproduce

systemctl start airsonic.service

### Version

11.0.2 (Stable)

### Operating System

Debian Bullseye

### Java Version

openjdk 11.0.18 2023-01-17

### Database

MariaDB 8.x

### Configuration paramter

I think it is not necessary ;-)

### language

French

**Comment by kagemomiji** [comment]
@microniko 
Do you use the `war` file from the release page?
This repository use Java 17 to build `war`.
Could you try java version 17.

**Comment by microniko** [comment]
@kagemomiji yes, I use the `war` file.
Java 17 is available in Debian. Sorry, I didn't know…
Really, with this Java version, it is better ;-)
Version [11.0.2-SNAPSHOT.20230308162611](https://github.com/kagemomiji/airsonic-advanced/releases/tag/11.0.2-SNAPSHOT.20230308162611) works perfectly !
Thanks for this Airsonic Fork ! <3
