### ISSUE TITLE
[Bug]: Unable to update from airsonic-advanced 10.6.0 (Crash after DB backup)

### ISSUE THREAD

**Issue by ThecaTTony** [kagemomiji/airsonic-advanced#151]
### What happened?

Hi, I'm trying to update airsonic-advanced 10.6.0 to this fork airsonic-kagemomiji but the process crash right after the backup of the old DB is made.

So far I've tried the following:

(With this fork)
JRE 17 running 11.1.0 which fails to upgrade the DB and that leads me to use the version recommended in readme.md
JRE 17 running 11.0.0-SNAPSHOT.20221224143241 or 11.0.0-SNAPSHOT.20221223170709 which lead to crash somewhere after the backup of the old DB is made.
JRE14 Crash with: Exception in thread "main" java.lang.UnsupportedClassVersionError...

(Original airsonic-advanced)
JRE 14 running 11.0.0-SNAPSHOT.20230217142243 same behavior (crash somewhere after the backup of the old DB is made).

In all attempts the necessary changes to airsonic.properties where made:

server.context-path=/airsonic --> server.servlet.context-path=/airsonic
server.use-forward-headers=true --> server.forward-headers-strategy=native

Debug mode wont add nothing relevant in the logs, just the same message copied below (log section).
After the crash with JRE 17 and 11.0.0-SNAPSHOT.20221224143241 the DB is identically to the backup, but one line is added to the end of airsonic.properties:
`spring.liquibase.parameters.defaultPodcastFolder=/var/lib/airsonic/podcasts
`

As I read (https://stackoverflow.com/a/53228215), to upgrade HSQLDB from 1.8 to 2.5 it is necessary to perform SHUTDOWN SCRIPT, but stopping the airsonic-advanced 10.6.0 service only runs SHUTDOWN as shown in the DEBUG log (or is it the same thing?):

`2023-03-17 00:57:55.574 DEBUG --- o.s.jdbc.core.JdbcTemplate               : Executing SQL statement [SHUTDOWN]`

### Steps to reproduce

1. Stop the service
2. Change JRE with version 17
3. Change airsonic.properties parameters
4. Change /var/lib/airsonic/airsonic.war with airsonic-11.0.0-SNAPSHOT.20221224143241.war
5. Start the service
6. Try the same with JRE 14
7. Try the same with JRE 14 and airsonic-advanced latest release.

### Version

11.1.x (Edge)

### Version Detail

11.0.0-SNAPSHOT.20221224143241

### Operating System

Ubuntu 22.04.2 LTS ARM64

### Java Version

openjdk version "17.0.6" 2023-01-17 or openjdk version "14.0.2" 2020-07-14

### Database

Other

### DB Detail

HSQLDB 1.8.0

### Configuration paramter

```
/var/lib/airsonic/db/airsonic.properties (DB)

#HSQL Database Engine 1.8.0.5
#Thu Mar 16 23:45:00 ART 2023
hsqldb.cache_version=1.7.0
hsqldb.defrag_limit=32
sql.enforce_strict_size=false
hsqldb.compatible_version=1.8.0
hsqldb.cache_scale=14
hsqldb.nio_data_file=true
version=1.8.0
runtime.gc_interval=0
readonly=false
hsqldb.cache_file_scale=8
hsqldb.cache_size_scale=8
hsqldb.log_size=64
hsqldb.script_format=0
hsqldb.default_table_type=memory
hsqldb.original_version=1.8.0
modified=yes
```

```
/var/lib/airsonic/airsonic.properties

# Airsonic preferences.  NOTE: This file is automatically generated. Do not modify while application is running

JWTKey=###
SettingsChanged=1670941232406
GettingStartedEnabled=false
IndexString=A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
IgnoredArticles=The El La Los Las Le Les
Shortcuts=
PlaylistFolder=/var/lib/airsonic/playlists
MusicFileTypes=aac flac m4a mp3
VideoFileTypes=
CoverArtFileTypes2=folder.jpg
SortAlbumsByYear=true
WelcomeTitle=###
WelcomeSubtitle=###
WelcomeMessage2=###
LoginMessage=###
Theme=black
LocaleLanguage=es
LocaleCountry=
LocaleVariant=
PodcastUpdateInterval=24
PodcastEpisodeRetentionCount=-1
PodcastEpisodeDownloadCount=1
PodcastFolder=/var/lib/airsonic/podcasts
DownsamplingCommand4=ffmpeg -i %s -map 0:0 -b:a %bk -vn -f mp3 -
HlsCommand3=ffmpeg -ss %o -t %d -i %s -async 1 -b:v %bk -s %wx%h -ar 44100 -ac 2 -v 0 -f mpegts -c:v libx264 -preset superfast -c:a libmp3lame -threads 0 -
IndexCreationInterval=1
IndexCreationHour=3
FastCacheEnabled=false
OrganizeByFolderStructure=true
ExcludePattern=
IgnoreSymLinks=false
DownloadBitrateLimit=0
UploadBitrateLimit=0
LdapEnabled=false
LdapUrl=
LdapSearchFilter=(sAMAccountName={0})
LdapManagerDn=
LdapAutoShadowing=false
SmtpServer=0.0.0.0
SmtpEncryption=None
SmtpPort=
SmtpUser=
SmtpFrom=
SmtpPassword=
CaptchaEnabled=false
ReCaptchaSiteKey=
server.context-path=/airsonic
server.use-forward-headers=true
#server.servlet.context-path=/airsonic
#server.forward-headers-strategy=native
EncryptionKeyPassword=###
EncryptionKeySalt=###
```

```
Command executed by the airsonic.service file:

/usr/bin/java -Xmx2G -Dairsonic.home=/var/lib/airsonic -Dserver.servlet.context-path=/airsonic -Dserver.port=8080 -jar /var/lib/airsonic/airsonic.war --server.address=localhost
```

### language

None

### Relevant log output

```console
2023-03-16 23:26:34.825  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database upgrade needed, from version 1.8.0 to 2.5
2023-03-16 23:26:34.834 DEBUG --- o.a.p.u.LegacyHsqlMigrationUtil          : Performing HSQLDB database backup...
2023-03-16 23:27:27.264  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database upgrade needed, from version 1.8.0 to 2.5
2023-03-16 23:27:27.272 DEBUG --- o.a.p.u.LegacyHsqlMigrationUtil          : Performing HSQLDB database backup...
2023-03-16 23:28:36.032  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database upgrade needed, from version 1.8.0 to 2.5
2023-03-16 23:28:36.047 DEBUG --- o.a.p.u.LegacyHsqlMigrationUtil          : Performing HSQLDB database backup...
2023-03-16 23:31:49.498  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database upgrade needed, from version 1.8.0 to 2.5
2023-03-16 23:31:49.505 DEBUG --- o.a.p.u.LegacyHsqlMigrationUtil          : Performing HSQLDB database backup...


Mar 16 23:10:00 mirta systemd[1]: Started Airsonic Media Server.
Mar 16 23:10:02 mirta java[212921]:            _                       _
Mar 16 23:10:02 mirta java[212921]:      /\   (_)                     (_)
Mar 16 23:10:02 mirta java[212921]:     /  \   _ _ __  ___  ___  _ __  _  ___
Mar 16 23:10:02 mirta java[212921]:    / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|
Mar 16 23:10:02 mirta java[212921]:   / ____ \| | |   \__ \ (_) | | | | | (__
Mar 16 23:10:02 mirta java[212921]:  /_/    \_\_|_|   |___/\___/|_| |_|_|\___|
Mar 16 23:10:02 mirta java[212921]:                                                
Mar 16 23:10:02 mirta java[212921]:                         11.0.0-SNAPSHOT
Mar 16 23:10:02 mirta java[212921]: 2023-03-16 23:10:02.961  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database upgrade needed, from version 1.8.0 to 2.5
Mar 16 23:10:02 mirta java[212921]: 2023-03-16 23:10:02.966 DEBUG --- o.a.p.u.LegacyHsqlMigrationUtil          : Performing HSQLDB database backup...
Mar 16 23:10:03 mirta systemd[1]: airsonic.service: Main process exited, code=killed, status=31/SYS
Mar 16 23:10:03 mirta systemd[1]: airsonic.service: Failed with result 'signal'.
Mar 16 23:10:03 mirta systemd[1]: airsonic.service: Consumed 5.678s CPU time.
```

**Comment by kagemomiji** [comment]
@ThecaTTony 
Please read README.md [here](https://github.com/kagemomiji/airsonic-advanced/blob/main/README.md#11x-series)

My fork was upgraded HSQL version for CVE.
If you use HSQLDB for 10.6.0, DB migration must fails. First upgrade to 11.0.0-SNAPSHOT.20221224143241 then upgrade to latest release.

**Comment by ThecaTTony** [comment]
I was able to update the database with another tool before running the latest version of this fork. I'm gonna leave the steps for anyone who has the same problem.

As commented in the report, the problem was related to the missing "SHUTDOWN SCRIPT;" necessary to upgrade the DB from 1.8.0 to 2.3.X-2.5.X. With the help of a tool called hsqldb-manager (https://github.com/IvoFritsch/hsqldb-manager) I take a copy of the DB, made the deploy and then upgrade.

1. Download and extract hsqldb-manager.zip
2. Move to the folder extracted, made a new folder called airsonic and copy a backup of the airsonic DB (airsonic.script airsonic.properties)
3. Start hsqldb-manager with the script or the bat file (whenever you are using linux or windows) and deploy the DB:
```
hsqlman.bat start
hsqlman.bat deploy airsonic
hsqlman.bat sqltool airsonic
```
4. Run "SHUTDOWN SCRIPT;" in the sqltool prompt and exit.
5. Stop hsqldb-manager:
`hsqlman.bat stop`
6. Copy the upgraded DB (both files) to the folder $AIRSONIC_HOME/db (keep a backup of the old DB just in case something goes wrong)
7. Start airsonic and enjoy.

Reference: http://www.hsqldb.org/doc/guide/deployment-chapt.html#dec_upgrade_database

**Comment by ThecaTTony** [comment]
Well, after a few crash from the new version (11.1.0) always when the automatic DB backup was running takes me to this bug report:

https://github.com/airsonic-advanced/airsonic-advanced/issues/617#issuecomment-917102721

Its seems that all my problem was because the restrictions in the systemd service file:

`SystemCallFilter=~@clock @debug @module @mount @obsolete @privileged @reboot @setuid @swap`
