### ISSUE TITLE
Migration from airsonic-advanced fork

### ISSUE THREAD

**Issue by dsiminiuk** [kagemomiji/airsonic-advanced#165]
If I'm already running the latest 11-SNAPSHOT from github.com/airsonic-advanced, what am I missing to launch the war file from the latest release here? 

I tried...
```
jounrnalctl -n 50
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/airsonic/player/Application has been compiled by a more recent version of the Java Runtime (class file versi <snipped>
```
Java info
```
> java --version
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```
Thanks in advance...

**Comment by bartmans** [comment]
Hi,

From the homepage: https://github.com/kagemomiji/airsonic-advanced:
Feature enhancements:
* Works with JDK17

**Comment by 8bitbuddhist** [comment]
Try using openJDK 17.

https://github.com/kagemomiji/airsonic-advanced#stand-alone-binaries
> You need a minimum Java Runtime Environment (JRE) of 1.8 for 10.6.x series, and 11 for 11.x onwards (including snapshots).
>
> For 11.x releases and onwards -> Java 17

**Comment by dsiminiuk** [comment]
@8bitbuddhist Well that was easy. Updated to openjdk-17-jre-headless and the previous Airsonic still works. Time for a snapshot and then I'll try the local war.

Thank you!

**Comment by dsiminiuk** [comment]
Worked great! HSQLDB updated to 2.7.1 all automatically.
