### ISSUE TITLE
[Bug]:  GET 	https://*****.org/script/mediaelement/mejs-controls.svg 404

### ISSUE THREAD

**Issue by nowheretobefound** [kagemomiji/airsonic-advanced#183]
### What happened?

I get 404 Not found for <span class="message-body-wrapper">

GET | https://*****.org/script/mediaelement/mejs-controls.svg
-- | --

</span>
And the play/pause button is missing. 

The context root for airsonic is /airsonic while it looks for the resource under / 

Apache as frontend proxy.

This setup has been working for many years, so some recent update broke it.

### Steps to reproduce

Load airsonic-advanced served from /airsonic/ context root observe wrong url for player buttons

### Version

11.1.x (Edge)

### Version Detail

11.1.2-SNAPSHOT.20230407154617 – April 7, 2023 at 3:46:17 PM UTC [Commit: da716c8d8f769c3bc095e04be17abb16b8abeb6b]

### Operating System

Linux

### Java Version

included in docker

### Database

PostgreSQL 13.x

### Configuration paramter

  airsonic:
    image: ghcr.io/kagemomiji/airsonic-advanced:${tag}
    restart: always
    user: "30:8"
    healthcheck:
      test: "curl -f http://localhost:4040/airsonic/rest/ping || false"
      interval: "60s"
      timeout: "3s"
      retries: 3
    volumes:
      - ${musicfolder}:/mnt/nas/common/Musikk
      - ${podcastfolder}:/mnt/nas/common/Podcasts
      - ${playlists}:/var/playlists
      - ${airsonicdata}:/var/airsonic
    ports:
      - ${httpPort}:4040

    environment:
      - CONTEXT_PATH=/airsonic
      - JAVA_OPTS=-Xmx1536m
      - spring_datasource_url=jdbc:postgresql://db:5432/${dbName}?stringtype=unspecified&raiseExceptionOnSilentRollback=false
      - spring_datasource_username=${dbUser}
      - spring_datasource_password=${dbPass}
      - spring_liquibase_parameters_userTableQuote="

### Proxy Server

Apache

### client detail

Firefox

### language

English

**Comment by nowheretobefound** [comment]
Relevant issue ?
https://github.com/mediaelement/mediaelement//issues/2874

**Comment by kagemomiji** [comment]
@nowheretobefound 
Could you try clearing your browser's cache?

**Comment by nowheretobefound** [comment]
Tnx for checking :), clearing caches, switching browser, incognito, still tries to load the elements from wrong context.

**Comment by nowheretobefound** [comment]
ghcr.io/kagemomiji/airsonic-advanced:pr-185 shows the play button and no errors. Kudos

**Comment by kagemomiji** [comment]
@nowheretobefound 
Thanks a lot! The latest version of Edge contains this fix. Please use it.
