### ISSUE TITLE
[Feature Request]: Replace DAO class with JPARepository due to SQL maintenance issues

### ISSUE THREAD

**Issue by kagemomiji** [kagemomiji/airsonic-advanced#212]
### Scope

Other

### What problem

The current implementation uses DAO classes to handle SQL queries, which can be difficult to maintain over time. DAO classes require developers to write raw SQL queries, which can lead to issues with readability and maintainability. 

### Feature

To address these issues, I recommend replacing DAO classes with JPARepository. JPARepository is a higher-level abstraction layer that eliminates the need to write raw SQL queries. This approach is more developer-friendly and easier to maintain over time. By using JPARepository, developers can focus on writing clean, readable code that is easy to maintain, rather than spending time on low-level SQL queries.

Overall, by replacing DAO classes with JPARepository, we can improve the maintainability of our codebase and reduce development time and costs.

- [x] AlbumDao.java
- [x] ArtistDao.java
- [x] AvatarDao.java
- [x] CoverArtDao.java
- [ ] DatabaseDao.java
- [x] InternetRadioDao.java
- [x] MediaFileDao.java
- [x] MusicFolderDao.java
- [x] PlayerDao.java
- [x] PlaylistDao.java
- [ ] PlayQueueDao.java
- [x] PodcastDao.java
- [x] RatingDao.java
- [x] ShareDao.java
- [x] SonosLinkDao.java
- [x] TranscodingDao.java
- [x] UserDao.java

**Comment by 8bitbuddhist** [comment]
This is a huge undertaking and I respect the effort that you're putting into this project. Thank you for keeping Airsonic alive! ❤
