### ISSUE TITLE
[Feature Request]: Allow to set up Admin user name

### ISSUE THREAD

**Issue by zc-devs** [kagemomiji/airsonic-advanced#253]
### Scope

Other

### What problem

Currently there is "no way" to change default `admin` username.

If I create new full permissions user (say, `root_admin`) and try to delete old default one, then I get:
```
There was an unexpected error (type=Internal Server Error, status=500).
org.springframework.dao.InvalidDataAccessApiUsageException: Can't delete admin user.; nested exception is java.lang.IllegalArgumentException: Can't delete admin user.
...
	at org.airsonic.player.controller.UserSettingsController.deleteUser(UserSettingsController.java:179)
	at org.airsonic.player.controller.UserSettingsController.doSubmitAction(UserSettingsController.java:151)
...
```

If I change name in database manually, then I loose [safety check](https://github.com/kagemomiji/airsonic-advanced/blob/304bebfa65f3b73c95fc7b6eccd98a5d4007795f/airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java#L190) mentioned above.

### Feature

I propose to make administrator name configurable.

1. Allow to set environment variable (Spring property) with custom admin username (and probably password) like Postgres do with `POSTGRES_USER` (and `POSTGRES_PASSWORD`), for example.
2. Only make configurable `USERNAME_ADMIN` in `UserDao`. Then we can change username manually in database and don't lose sefety check at least.

**Comment by The-Exterminator** [comment]
Make a user with admin priv, and delete the admin
