### ISSUE TITLE
[Feature Request]: Local Artist Image

### ISSUE THREAD

**Issue by luxdi** [kagemomiji/airsonic-advanced#254]
### Scope

GUI

### What problem

For as long as I can remember the pull from last.fm for the Artist Image just gives a big white star. 

### Feature

I have a folder.jpg file for the artist in every one of my artist folders. Would be possible to be able to use locally stored files for the Artist Image instead of the failed call to last.fm which generates the white star.

**Comment by The-Exterminator** [comment]
or take the image from spotify or tidal

**Comment by fault1er1** [comment]
And please... for searching purposes use the Artist Name from the tags and not the filename from the filesystem.

**Comment by boudafc** [comment]
> or take the image from spotify, tidal or fanart.tv

It seems to be a better idea. I have made a little research and after subscribing to the API from last.fm, it seems to return a "star" (https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png) as image even if there is really an image for the artist in last.fm website.

**Comment by fault1er1** [comment]
Hi kagemomiji,

thank you for the implementation of this useful feature!

Is it possible to change the display of the images in such a way that the aspect ratio is preserved? Unfortunately, a lot of band logos/pictures are now distorted. Just like the album covers, when it's a cover of a tape or another not-cd aspect ratio.

Thanks in advance!
