### ISSUE TITLE
[Bug]: m4b (apple itunes) cant Load cover art + cant forward and back time line of file 

### ISSUE THREAD

**Issue by masterwishx** [kagemomiji/airsonic-advanced#265]
### What happened?

m4b (apple itunes) cant Load cover art + cant forward and back time line of file 

![image](https://github.com/kagemomiji/airsonic-advanced/assets/28630321/9b8d9b8a-01ae-45e1-9298-5b9de2f570c5)

![image](https://github.com/kagemomiji/airsonic-advanced/assets/28630321/ea505b91-2455-4169-ae10-18c79d6d6a7c)

![image](https://github.com/kagemomiji/airsonic-advanced/assets/28630321/fa6e5d75-965b-4e9c-a450-60d14fa6d756)

### Steps to reproduce

play m4b file

### Version

11.1.x (Edge)

### Version Detail

11.1.3-SNAPSHOT.20230814141332 – 14 августа 2023 г., 17:13:32 IDT [Commit: fce8198f02e85f3e098e9fa49d1e1ef690aa508c]

### Operating System

Docker in Unraid (linux x64)

### Java Version

java 17.0.5

### Database

MariaDB 8.x

### Configuration paramter

...

### language

None

### Relevant log output

```console
Failed to find cover art tag in /unraid_games_disk_7/Герберт Фрэнк - Хроники Дюны/3. Герберт Фрэнк - Дюна 3. Дети Дюны [Сергей Чонишвили] m4b/Дети Дюны. Часть 2.m4b
16.08.2023 13:23:06
16.08.2023 13:23:06
org.jaudiotagger.audio.exceptions.CannotReadVideoException: This file appears to be an Mp4 Video file, video files are not supported
```

**Comment by masterwishx** [comment]
any new for it ?
Also error when sheduled scanning :   

![image](https://github.com/kagemomiji/airsonic-advanced/assets/28630321/c61d5cdf-09a1-4ff7-b65e-d6d08433995a)

**Comment by masterwishx** [comment]
@kagemomiji can it be fixed in future?

**Comment by masterwishx** [comment]
> I apologize for the delay. I've been trying to reproduce the issue on my end with an m4b file I created myself, but I haven't been able to replicate it.

its OK, Thanks for your work .
Do you have discord or telegram maybe  for message ?

**Comment by masterwishx** [comment]
Please contact me in telegram or discord .... 
its Russian version of Frenk Gerberd .    the Dune 
https://www.litres.ru/audiobook/frenk-gerbert/deti-duny-66853808/

**Comment by masterwishx** [comment]
@kagemomiji i downloaded new files and seems i have other problem when trying to  forward and back time line of file : 

![image](https://github.com/kagemomiji/airsonic-advanced/assets/28630321/68b2c1c2-4d7c-4507-b7ad-13347217156a)

**Comment by kagemomiji** [comment]
@masterwishx 
I've created a Discord account with the same name as my GitHub account, so please contact me there.

**Comment by masterwishx** [comment]
@kagemomiji i sended you a friend request ...
but like i said in befor https://github.com/kagemomiji/airsonic-advanced/issues/265#issuecomment-1967307195
i downloaded new files it seems the problem fixed with cover art but forward and back time line have another issue `broken pipe`
but after some minutes its playing again from where forwarded ....

**Comment by kagemomiji** [comment]
@masterwishx 
I have added a feature that splits and displays m4b audiobook formats by chapter. 
I have confirmed that it can successfully play the file you provided. 
Could you please try out `ghcr.io/kagemomiji/airsonic-advanced:pr-409`? 
Details about the configuration are written in the pull request. #409

**Comment by masterwishx** [comment]
> @masterwishx I have added a feature that splits and displays m4b audiobook formats by chapter. I have confirmed that it can successfully play the file you provided. Could you please try out `ghcr.io/kagemomiji/airsonic-advanced:pr-409`? Details about the configuration are written in the pull request. #409

Thanks, it seems working fine but have some errors in log when trying to move forward by mouse : 

![image](https://github.com/kagemomiji/airsonic-advanced/assets/28630321/088c55f0-8ca3-43ce-b377-e18760cdaf88)

![image](https://github.com/kagemomiji/airsonic-advanced/assets/28630321/12f1c2c3-5b2a-4d6f-9170-5c67f66505af)

![image](https://github.com/kagemomiji/airsonic-advanced/assets/28630321/a2dc3540-9fe0-456e-a8c2-f65c79334395)

**Comment by masterwishx** [comment]
checked in local net http://192.168.0.199:4040/index

**Comment by masterwishx** [comment]
@kagemomiji also in music.mysite.com same ...
i will send you log in discord ...

**Comment by kagemomiji** [comment]
@masterwishx 
I have created fixed docker image. Could you pull `pr-409` image and try it again?

**Comment by masterwishx** [comment]
> @masterwishx I have created fixed docker image. Could you pull `pr-409` image and try it again?

No errors in logs , its Fine now . Thank you for your work ...
