### ISSUE TITLE
[Bug]: Special Characters in Folder and/or Filename causes Search to crash

### ISSUE THREAD

**Issue by C9Glax** [kagemomiji/airsonic-advanced#278]
### What happened?

The character-string `ಠ ᴥ ಠ` caused airsonic to return /error when searching for another part of the same name.
Metadata seems to handle it somewhat better

### Steps to reproduce

Have a filename with the character-string `ಠ ᴥ ಠ`

### Version

11.1.x (Edge)

### Version Detail

11.1.3-SNAPSHOT.20230904021809

### Operating System

Debian 12

### Java Version

Docker openjdk 17.0.5 2022-10-18

### Database

Other

### DB Detail

Docker

### Configuration paramter

Docker
```
environment:
    - TZ = Europe/Berlin
    - PUID=1000
    - PGID=1000
    - JAVA_OPTS='-Dserver.forward-headers-strategy=native'
```

### language

None

**Comment by kagemomiji** [comment]
@C9Glax 

I have put a file which has `ಠ ᴥ ಠ` in its filename as the following folder structure, but I have not reproduced your error yet. Could you provide me your folder structure?


```
airsonic default music folder
└── 278_ಠ ᴥ ಠ
    └── ಠ ᴥ ಠ_test_album
        └── ಠ ᴥ ಠ_test.mp3
```

**Comment by C9Glax** [comment]
Sure thing.

```
└── Mox ಠ ᴥ ಠ
        └──  Rent Free (2021)
                 └── Mox ಠ ᴥ ಠ - Rent Free - 06 - Erp.mp3
```
Playing songs still worked, just search crashed/errored.

**Comment by C9Glax** [comment]
Okay, I had renamed the files to get the search working, but I jsut tried to get the same error and now I can't reproduce it either...
If you want close, should it happen again I will @ you

**Comment by kagemomiji** [comment]
@C9Glax 
I will close this issue for now. If there are any errors related with this issue, please reopen it.
