### ISSUE TITLE
[Bug]: Unable to update admin email/password on latest

### ISSUE THREAD

**Issue by Rumbles** [kagemomiji/airsonic-advanced#351]
### What happened?

I tried setting up airsonic using the docker compose file, I configured it to use a postgres database, and I was able to connect, it told me to update the admin password, I did this and then created a new user

The next time I came to log in it warned me the admin password hadn't been changed.

I tried changing it a number of times, to no avail, I checked for errors in the container logs, but didn't see anything in the docker logs. I noticed that when I updated the admin password and email, after hitting save (and it telling me changes saved) that the email address on the admin user had not been updated (nothing appeared in the credentials tab either).

I stopped my containers, deleted the database, changed the compose file to use the stable tag and tried again, and I was able to create a new password and update the email address, I then deleted the old default plaintext password in the creds tab and logged out and it works.

TO make certain, I then deleted my dc again, reverted to latest and tried again, I was not going mad, adding email and creds to the admin user doesn't appear to work for me on latest, reverting to stable fixes.

I will try using latest after updating the admin creds first

### Steps to reproduce

1. Run latest on docker compose (with postgres) from scratch
2. Try to add an email address and new credentials to admin user
3. Check if creds were added

### Version

11.1.x (Edge)

### Version Detail

11.1.3-SNAPSHOT.20240124131128

### Operating System

Linux

### Java Version

17 (not sure it's from the container)

### Database

PostgreSQL 14.x

### Configuration paramter

The only config I used was reverse proxy for nginx

### Proxy Server

nginx 1.2

### client detail

Firefox

### language

English (United Kingdom)

**Comment by kagemomiji** [comment]
@Rumbles 
Thank you for your feedback. 
I was able to reproduce the issue and identify the cause. 
The updated Docker image is available `ghcr.io/kagemomiji/airsonic-advanced:pr-352` , and I would appreciate it if you could update the image in your docker-compose file to this new version and confirm if the issue has been resolved.

**Comment by Rumbles** [comment]
Hi @kagemomiji, thanks for a the swift reply and PR, I can confirm, I started a new instance with a fresh DB, admin user email now changes and new creds are created, this can be closed once that change is merged
