### ISSUE TITLE
[Bug]: Settings not saved for Transcoding option: "Enable transcoding settings for all existing and new players."

### ISSUE THREAD

**Issue by jibbel23** [kagemomiji/airsonic-advanced#370]
### What happened?

Unchecking the option "Enable transcoding settings for all existing and new players." and clicking save results in the checkbox remaining enabled and default transcoding still active.

### Steps to reproduce

Uncheck the "Enable transcoding settings for all existing and new players." in Transcoding settings.
Click Save.

### Version

11.1.2 (Stable)

### Version Detail

11.1.3

### Operating System

Docker

### Java Version

11.1.3 stable version

### Database

Mysql 10.x

### Configuration paramter

Default

### language

None

**Comment by jibbel23** [comment]
This is a bug from the legacy Airsonic codebase that has been around for a long time and deserves to finally get fixed. Users have had to disable transcoding on a per player basis after they're created as a work-around. With audio sources increasingly moving to higher than MP3 bitrates, this feature will be useful to allow Hi-Res audio files by default while still letting mobile users transcode while on cellular data. Thanks!

**Comment by kagemomiji** [comment]
@jibbel23 
The option "Enable transcoding settings for all existing and new players" is designed to select whether the added transcoding settings will be enabled by default for both existing and new players when adding new transcoding settings. 
It is not intended to enable or disable all existing transcoding settings by default.

With the changes in #375, I have introduced a new column `(Default)` for each transcoding setting, which allows you to switch this option. While it's not possible to change this setting for existing players, you will now be able to set transcoding options to be enabled or disabled by default for any new players created henceforth.

**Comment by jibbel23** [comment]
I added comment above, I understand it's meant to be the default and should function as such for new players. The goal for users like me is to have no transcoding by default, and the ability to customize as needed for each player after creation. I might be wrong, but I would think transcoding is becoming more and more of an edge case and should be off unless needed. Either way, let's allow users to decide.

I'll try out the new release and see if the new column works out as intended. Thx for the attention
