### ISSUE TITLE
[Bug]: Now Playing is completely empty?

### ISSUE THREAD

**Issue by DutchComputerKid** [kagemomiji/airsonic-advanced#381]
### What happened?

Since the Thymeleaf UI update, now playing seems to be completely dead.
The iframe is there, and there is a HTML div but with multiple people playing it just stays empty.

Now Playing was already a bit buggy with it not clearing or not updating the time after someone has left until an hour had passed and the queue would be cleared. (60 minutes by default)

### Steps to reproduce

1. Play anything
2. Right side of the screen stays empty and does not show now playing, or anything recently played.

### Version

11.1.x (Edge)

### Version Detail

11.1.4-SNAPSHOT.20240221145945

### Operating System

Debian 12

### Java Version

OpenJDK Runtime Environment (build 17.0.10+7-Debian-1deb12u1)

### Database

Other

### DB Detail

Built-In

### Configuration paramter

Same as all my other bug reports

### Proxy Server

NGINX

### client detail

Chrome, Pale Moon, Firefox

### language

English

**Comment by bartmans** [comment]
+1, also in Edge. Also checked in latest Stable, but there Now playing  works.

**Comment by kagemomiji** [comment]
@bartmans @DutchComputerKid 
I have fixed the WAR file and Docker image. Could you please test whichever you prefer?

war file [zip](https://github.com/kagemomiji/airsonic-advanced/actions/runs/8066346784/artifacts/1278985514)
docker image: `ghcr.io/kagemomiji/airsonic-advanced:pr-385`

**Comment by DutchComputerKid** [comment]
Had to wait for a new war file since the one in these comments was gone by the time I saw this. But yes, all is well now
