### ISSUE TITLE
[Bug]: Editing a large playlist moves tracks at random

### ISSUE THREAD

**Issue by Neogrey** [kagemomiji/airsonic-advanced#401]
### What happened?

When I remove a track from my playlist or move the position, it seems to randomly move some tracks to a different position in the playlist. Which results in a mess in the playlist. The playlist has around 200 tracks.

I have tried to export/import the playlist with the same result. And deleting the existing database didn't help either. I am at the end of my ideas.

[Bildschirmaufzeichnung vom 2024-03-23, 14-13-26.webm](https://github.com/kagemomiji/airsonic-advanced/assets/10816058/b50632df-07ef-45e1-9c16-f57c9c3485b2)

### Steps to reproduce

1. Edit a large playlist (move/delete tracks)
2. Random tracks are moved in the playlist

### Version

11.1.x (Edge)

### Version Detail

11.1.3

### Operating System

Docker

### Java Version

Apache Tomcat/9.0.83, java 17.0.5

### Database

Other

### DB Detail

Embedded database 

### Configuration paramter

  airsonic-advanced:
    image: ghcr.io/kagemomiji/airsonic-advanced:stable
    container_name: airsonic-advanced
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - CONTEXT_PATH= #optional
      - JAVA_OPTS=-Dserver.forward-headers-strategy=native
    volumes:
      [...]
    ports:
      - 4040:4040 # HTTP
    restart: unless-stopped

### language

None

**Comment by nRaecheR** [comment]
Yeah, this is a killer and I experience it since ages ago. It makes the whole playlist functionality unusable. There seems no system behind it, it behaves like some kind of shuffle.

It happens also when you add a song to an existing playlist from a third-party app, not only from the web interface.
