### ISSUE TITLE
[Bug]: Player selection missed in lastest releases and foreign chars in some places

### ISSUE THREAD

**Issue by Dikakus** [kagemomiji/airsonic-advanced#404]
### What happened?

In the latest releases, the player selector (in the lower left corner next to the play button) is missing. As a result, I can't switch between different players, and I don't know which one I'm currently using.

Snapshot from last stable release:
![Airsonic-With-Player](https://github.com/kagemomiji/airsonic-advanced/assets/14204887/029acae8-0c7d-41f9-ba21-1957ff2095c1)

On the other hand, non-English characters are displayed as html entities in some pages, such as the Spanish letter "ñ"  in the Playlist page.

Snapshot from last edge release:
![Airsonic-Tilde](https://github.com/kagemomiji/airsonic-advanced/assets/14204887/3a7529fd-6880-46c4-bdb2-104f30c2a462)

Thank you.

### Steps to reproduce

Accessing in the new release of Airsonic Advanced.

### Version

11.1.x (Edge)

### Version Detail

11.1.4-SNAPSHOT.20240325121919

### Operating System

Linux, Debian Bookworm in a Raspberry Pi 4

### Java Version

openjdk 17.0.10 2024-01-16

### Database

Other

### DB Detail

Build-in database

### Configuration paramter

[Unit]
Description=Airsonic Media Server
After=local-fs.target remote-fs.target network.target var-airsonic.service
Requires=var-airsonic.service
Wants=var-airsonic.service

[Service]
Type=simple
ExecStartPre=/bin/sleep 30
Environment="JAVA_JAR=/srv/airsonic/airsonic.war"
##Environment="JAVA_OPTS=-Xmx2048m -XX:MaxPermSize=1024m"
Environment="JAVA_OPTS=-Xmx2048m"
Environment="AIRSONIC_HOME=/var/airsonic"
Environment="PORT=8085"
Environment="CONTEXT_PATH=/airsonic"
Environment="DEBUG_LEVEL=WARN"
Environment="JAVA_ARGS="
EnvironmentFile=-/etc/sysconfig/airsonic
ExecStart=/usr/bin/java \
          $JAVA_OPTS \
          -Dairsonic.home=${AIRSONIC_HOME} \
          -Dserver.forward-headers-strategy=native \
          -Dserver.servlet.context-path=${CONTEXT_PATH} \
          -Dserver.port=${PORT} \
          -Dlogging.level.org.airsonic=${DEBUG_LEVEL} \
          -jar ${JAVA_JAR} $JAVA_ARGS

User=airsonic
Group=airsonic

# See https://www.freedesktop.org/software/systemd/man/systemd.exec.html
# for details
DevicePolicy=closed
DeviceAllow=char-alsa rw
NoNewPrivileges=yes
PrivateTmp=false
PrivateUsers=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
RestrictNamespaces=yes
RestrictRealtime=yes
SystemCallFilter=@basic-io @file-system @chown @network-io @sync @timer @signal @process @system-service
ReadWritePaths=/var/airsonic

# You can uncomment the following line if you're not using the jukebox
# This will prevent airsonic from accessing any real (physical) devices
#PrivateDevices=yes

# You can change the following line to `strict` instead of `full`
# if you don't want airsonic to be able to
# write anything on your filesystem outside of AIRSONIC_HOME.
ProtectSystem=full

# You can uncomment the following line if you don't have any media
# in /home/…. This will prevent airsonic from ever reading/writing anything there.
#ProtectHome=true

# You can uncomment the following line if you're not using the OpenJDK.
# This will prevent processes from having a memory zone that is both writeable
# and executeable, making hacker's lifes a bit harder.
#MemoryDenyWriteExecute=yes

[Install]
WantedBy=multi-user.target
WantedBy=var-airsonic.mount

### language

Spanish

**Comment by kagemomiji** [comment]
@Dikakus 
I have created fixed [war file](https://github.com/kagemomiji/airsonic-advanced/actions/runs/8588446763/artifacts/1391880017).  Could you please test this?

**Comment by Dikakus** [comment]
Hi, @kagemomiji !! Thank you so much!! The player selector has returned, and I can choose the player that I'm interested in:

![image](https://github.com/kagemomiji/airsonic-advanced/assets/14204887/011daa9b-792c-4fc2-8a86-1a53e5218554)


I know that foreign chars are a different issue and maybe I should have opened another one. The "ñ" is now fine but there are other words with html entities (I've detected in the previous screenshoot and in the login page):

Login page:
![image](https://github.com/kagemomiji/airsonic-advanced/assets/14204887/4d9f24ad-3ffd-4b61-8f9d-6ba403f04149)

This page works now:
![image](https://github.com/kagemomiji/airsonic-advanced/assets/14204887/51212fa0-6bcf-436e-9c58-0c370ef9181e)

Maybe I could lend you a hand reviewing these words if you tell me how I should do it.

**Comment by kagemomiji** [comment]
@Dikakus 

> Thank you so much!! The player selector has returned, and I can choose the player that I'm interested in:

Great! Thank you.

> I know that foreign chars are a different issue and maybe I should have opened another one.

It's fine, it doesn't bother me.

I've made some further modifications. Could you please check if there are any mistakes?
[fixed war file](https://github.com/kagemomiji/airsonic-advanced/actions/runs/8599870961/artifacts/1394063668)

**Comment by Dikakus** [comment]
Everything is perfect. I took a quick walk through some pages and all the text is fine now. Thanks again @kagemomiji for your work and effort. ^_^
