### ISSUE TITLE
[Feature Request]: Will the latest version of Airsonic-Advanced also work with OpenJDK 22?

### ISSUE THREAD

**Issue by litebito** [kagemomiji/airsonic-advanced#411]
### Scope

Other

### What problem

(this is more of a question than a request)
Java LTS versions.
The latest Java OpenJDK LTS  version is 21

### Feature

Will Airsonic-Advanced run with OpenJDK 21 (LTS) ?

**Comment by kagemomiji** [comment]
@litebito 
Hi. I have added JDK 21 of Eclipse Temurin to CI, and it seems work.
Do you want to know about JDK 22?

**Comment by litebito** [comment]
Hi,
actually, JDK 21 is fine, as that is the latest LTS ( JDK 22 is a short life version), thanks.
I'm planning to setup a fresh new server (currently still running on CentOS 7) , based on CentOS 9 Stream, so I prefer to use the most recent LTS versions of components that matter.

**Comment by kagemomiji** [comment]
@litebito 
Thank you. I see.
I close this issue as resolved.
