### ISSUE TITLE
[Bug]: The following artifacts could not be resolved: com.github.muff1nman.chameleon:core:jar:2.0.0-RELEASE

### ISSUE THREAD

**Issue by jhonny-oliveira** [kagemomiji/airsonic-advanced#414]
Hi!

> What happened?

I'm getting this error when I try to build the project:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Airsonic 11.1.3-SNAPSHOT:
[INFO] 
[INFO] Airsonic ........................................... SUCCESS [  0.447 s]
[INFO] Subsonic REST API .................................. SUCCESS [  3.073 s]
[INFO] Sonos API .......................................... SUCCESS [  3.305 s]
[INFO] Airsonic Main ...................................... FAILURE [ 14.657 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.789 s
[INFO] Finished at: 2024-04-11T10:32:17+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project airsonic-main: Could not resolve dependencies for project org.airsonic.player:airsonic-main:war:11.1.3-SNAPSHOT: The following artifacts could not be resolved: com.github.muff1nman.chameleon:core:jar:2.0.0-RELEASE, com.github.muff1nman.chameleon:playlist-xspf:jar:2.0.0-RELEASE, com.github.muff1nman.chameleon:playlist-all:jar:2.0.0-RELEASE: Could not find artifact com.github.muff1nman.chameleon:core:jar:2.0.0-RELEASE in 4th-line-http-unblocker (http://4thline.org/m2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :airsonic-main

```

I can't find these artifacts/versions anywhere, maybe related to log4j CVE. Where may I retrieve the missing artifacts? Is there a workaround?

> Steps to reproduce

`
mvn clean package
`

> Version

`
11.1.3 (stable)
`

> Operating system

`
Ubuntu 23.10
`

> Java Version

`
openjdk version "17.0.10" 2024-01-16
`

Thank you!

**Comment by kagemomiji** [comment]
@jhonny-oliveira 
com.github.muff1nman.chameleon:core:jar:2.0.0-RELEASE is in local repo.
https://github.com/kagemomiji/airsonic-advanced/tree/main/repo/com/github/muff1nman/chameleon/core/2.0.0-RELEASE
Could you check if the `repo` directory is in root directory of your cloned repository?

**Comment by kagemomiji** [comment]
@jhonny-oliveira 
> If I may, I intend to replace the old release of airsonic (https://xtradeb.net/apps/airsonic) with this version. Is there any caveat or incompatibility I should be aware of?
I intend to keep the same system configuration as before:

Please read https://github.com/kagemomiji/airsonic-advanced#compatibility-notes.

> And one last question. airsonic is presenting this "New version available. Download Airsonic 11.1.3 here."/"11.1.3-SNAPSHOT.20240411173301 \u2013 April 11, 2024 at 7:33:01 PM CEST [Commit: UNKNOWN]", although, this is exactly the version I just built: [Stable Release 11.1.3](https://github.com/kagemomiji/airsonic-advanced/releases/tag/11.1.3). How can I patch it to show the correct version info?

The pom.xml that removes SNAPSHOTs is generated only in the CI process, so the code will still include SNAPSHOT. If this concerns you, please execute the following command and then build it afterward.

`mvn versions:set -DremoveSnapshot=true`

**Comment by jhonny-oliveira** [comment]
Many thanks for the clarifications and for your work in this project!
