### ISSUE TITLE
UPNP/DLNA not working correctly

### ISSUE THREAD

**Issue by KeenVox** [kagemomiji/airsonic-advanced#474]
Hi,
I'm using airsonic in a local network, activated Upnp/DLNA. LAN adress is correct. I can see my folders and files from my UPNP devices but I can't play them.

In the logs there doesn't seem to be a problem. All I get is: 
2024-05-20 21:54:43.522 INFO --- o.a.p.s.u.DispatchingContentDirectory : UPnP request - objectId: 36007, browseFlag: BrowseMetadata, filter: *, firstResult: 0, maxResults: 1

Anything I'm missing here?

I run airsonic on a raspberrypi with debia bullseye in standalon .war mode.

**Comment by luxdi** [comment]
I have exactly the same set up as you (RPi/Standalone war) and UPNP/DLNA works fine for me. On the settings page the example given is "http://192.168.0.2/airsonic/". However mine is set like this "http://192.168.0.2:8080" - I changed it way back for some reason I can't recollect now, but try that.

**Comment by KeenVox** [comment]
Tried that but still doesn't work correct. Though I get a different error message now:

2024-05-23 19:47:34.625 ERROR --- o.a.p.s.LoggingExceptionResolver         : 192.168.178.87: An exception occurred while loading htt>

java.lang.NullPointerException: Cannot invoke "org.airsonic.player.domain.User.getUsername()" because "user" is null

**Comment by kagemomiji** [comment]
@KeenVox @DutchComputerKid 
I have created fixed `war` file.  Could you try? 
[war file in zip](https://github.com/kagemomiji/airsonic-advanced/actions/runs/9289366815/artifacts/1549073106)

**Comment by KeenVox** [comment]
> @KeenVox @DutchComputerKid I have created fixed `war` file. Could you try? [war file in zip](https://github.com/kagemomiji/airsonic-advanced/actions/runs/9289366815/artifacts/1549073106)

I tried an now it's working fine. :-)
