### ISSUE TITLE
[Bug]: Favorite albums/artists not in sync between clients & DSub errors when marking as favorite

### ISSUE THREAD

**Issue by Faeb35** [kagemomiji/airsonic-advanced#497]
### What happened?

I'm using Sonixd (https://github.com/jeffvli/sonixd), DSub (https://github.com/daneren2005/Subsonic) and the Airsonics own webinterface.

While using these three clients, I realized, that they have different behaviours when it comes to using the Favorites functions.

1. Albums marked as favorites are different from Sonixd vs. DSub/Airsonic webinterface. When I mark an album as favorite in Sonixd, it's not marked as favorite in DSub & Airsonic webinterface. Also the other way arround. It look's like the information is stored seperately for Sonixd vs DSub/Airsonic webinterface in the datebase (just guessing).
There also seams to be the same issue with artists marked as favorite (just from a quick test, don't use that actually).
But no issue with tracks marked as favorite, they are all in sync between Sonixd/DSub/Webinterface.

DSub seams to use this call
GET /rest/getStarred.view?u=XXXXXX&s=XXXXXX&t=XXXXXX&v=1.2.0&c=DSub&musicFolderId=0&X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=5b7964b9-fde5-4d83-b327-df3c1772d575
vs. Sonixd seams to use this call
GET /rest/getStarred2.view?u=XXXXXX&s=XXXXXX&t=XXXXXX&v=1.13.0&c=sonixd&f=json&X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=77f6fc7a-0355-4bee-9506-e6dcb650a39a

2. When marking albums or tracks as favorite in DSub, I'm always getting an error, that the operation couldn't be finished and that I should try again later. But actually it was really marked as favorite when I have a look at the Airsonic webinterface or restart DSub. I'm guessing that DSub expects some sort of acknowledgement from the API which is missing (worked with earlier versions of Airsonic and DSub).

DSub seams to use these calls
Track
GET /rest/star.view?u=XXXXXX&s=XXXXXX&t=XXXXXX&v=1.2.0&c=DSub&id=709053&X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=ec74b80c-d924-43e6-a923-d2e9c35ea327
Album
GET /rest/star.view?u=XXXXXX&s=XXXXXX&t=XXXXXX&v=1.2.0&c=DSub&id=150177&X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=1d666502-b74c-4dd3-9563-e6070723b073

When I run /rest/star.view in a browser, I'm seeing a HTTP 200 status with an empty content body.

### Steps to reproduce

1. Mark album as favorite in Sonixd
2. Check in the webinterface
3. Mark an album as favorite in the webinterface
4. Check in Sonixd

1. Mark a track or an album as favorite in DSub
2. Check the error message

### Version

11.1.4-SNAPSHOT (Edge)

### Version Detail

11.1.4-SNAPSHOT.20240504134115

### Operating System

Windows Server 2022 (21H2)

### Java Version

openjdk version "20.0.1" 2023-04-18

### Database

Other

### DB Detail

Default HSQLDB

### Configuration paramter

JWTKey=XXXXXXX
SettingsChanged=1709283431404
GettingStartedEnabled=false
PodcastUpdateInterval=168
PodcastEpisodeRetentionCount=10
PodcastEpisodeDownloadCount=-1
PodcastFolder=\XXXXXXXXX\Podcasts
IndexString=A \u00C4 B C D E F G H I J K L M N O \u00D6 P Q R S T U \u00DC V W X-Z(XYZ)
IgnoredArticles=The Tha El La Los Las Le
Shortcuts=New Incoming Podcast
PlaylistFolder=c:\playlists
MusicFileTypes=mp3 ogg oga aac m4a m4b flac wav wma aif aiff ape mpc shn mka opus
VideoFileTypes=flv avi mpg mpeg mp4 m4v mkv mov wmv ogv divx m2ts webm
CoverArtFileTypes2=cover.jpg cover.png cover.gif covers.jpg covers.png folder.jpg jpg jpeg gif png
SortAlbumsByYear=true
WelcomeTitle=
WelcomeSubtitle=
WelcomeMessage2=
LoginMessage=
Theme=default
LocaleLanguage=en
LocaleCountry=
LocaleVariant=
IndexCreationInterval=1
IndexCreationHour=2
FastCacheEnabled=false
OrganizeByFolderStructure=true
ExcludePattern=
IgnoreSymLinks=false
DownloadBitrateLimit=0
UploadBitrateLimit=0
LdapEnabled=false
LdapUrl=ldap://host.domain.com:389/cn=Users,dc=domain,dc=com
LdapSearchFilter=(sAMAccountName={0})
LdapManagerDn=
LdapAutoShadowing=false
SmtpServer=localhost
SmtpEncryption=None
SmtpPort=25
SmtpUser=
SmtpFrom=XXXXXXX
CaptchaEnabled=false
ReCaptchaSiteKey=XXXXXXX
FullScanOnce=false
CoverArtSource=TAGFILE
HlsCommand3=ffmpeg -ss %o -t %d -i %s -async 1 -b:v %bk -s %wx%h -ar 44100 -ac 2 -v 0 -f mpegts -c:v libx264 -preset superfast -c:a libmp3lame -threads 0 -
spring.liquibase.parameters.defaultPodcastFolder=\XXXXXXXXX\Podcasts
EncryptionKeyPassword=XXXXX
EncryptionKeySalt=XXXX
UploadsFolder=%{['USER_MUSIC_FOLDERS'][0]}/Incoming
EnableCueIndexing=false
HideIndexedFiles=false
FullScan=false
ClearFullScanSettingAfterScan=false
spring.liquibase.parameters.mysqlVarcharLimit=384
DbBackupUpdateInterval=168
DbBackupRetentionCount=3

### Proxy Server

IIS

### client detail

Sonixd, DSub, Webinterface

### language

German

### Relevant log output

```console
No errors in airsonic.log
```

**Comment by Faeb35** [comment]
Here the calls that are used to mark samething as favorite:
DSub
Track
GET /rest/star.view?u=XXXXXX&s=XXXXXX&t=XXXXXX&v=1.2.0&c=DSub&id=709053&X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=ec74b80c-d924-43e6-a923-d2e9c35ea327
Album
GET /rest/star.view?u=XXXXXX&s=XXXXXX&t=XXXXXX&v=1.2.0&c=DSub&id=150177&X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=1d666502-b74c-4dd3-9563-e6070723b073

Sonixd
Track
GET /rest/star.view?id=689444&u=XXXXXX&s=XXXXXX&t=XXXXXX&v=1.13.0&c=sonixd&f=json&X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=4d0b097f-0c17-4819-aa6a-23fb0f30d9fa
Album
GET /rest/star.view?albumId=49928&u=XXXXXX&s=XXXXXX&t=XXXXXX&v=1.13.0&c=sonixd&f=json&X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=131808ed-4667-46dc-af90-7b6801733d8f

**Comment by kagemomiji** [comment]
@Faeb35 
I have created fix war file [here](https://github.com/kagemomiji/airsonic-advanced/actions/runs/9508503570/artifacts/1600292429)
Could you try it?

**Comment by Faeb35** [comment]
@kagemomiji Thank you so much! This fixed the issue with DSub. Don't getting errory anymore when marking songs/albums as favorite!! Your the best!

But still having the issue, that albums marked as favorite in Sonixd are not showing as favorite album in DSub/Webinterface (and the other way around). Also tried to go with a complete new installation/config using the war-file you provided. Same issue.
Since this seams to be another (not directly related) issue, should I create a separte issue for that in GitHub?

**Comment by kagemomiji** [comment]
@Faeb35 
The reason for this issue is that WebUI/DSub and Sonixd operate based on different information sources. 
WebUI/DSub functions based on the folder structure (/artist/album/track) to determine albums and artists. 
On the other hand, Sonixd operates based on embedded file information, such as ID3 tag data. 
As a result, there is a lack of synchronization of Stars between WebUI/DSub and Sonixd.

So, If you want the synchronization between WebUI/DSub and Sonixd, please publish `Feature Request`  issue.
