### ISSUE TITLE
[Feature Request]: Permanently delete guest user

### ISSUE THREAD

**Issue by brokoler** [kagemomiji/airsonic-advanced#505]
### Scope

GUI

### What problem

Airsonic automatically creates a "guest" user, which is shown via "WebUI -> Settings -> Users -> Select User"
After deleting the user it is reappearing automatically after some time.

I see it as an security issue, since I don't know how the guest user is created and which password is assigned to it (Probably some default password that can be bruteforced).

### Feature

Guest user should not be created at all and deleting it should be permanent.

**Comment by kagemomiji** [comment]
@brokoler 
`guest` user is automatically created with random password which length is 30.
https://github.com/kagemomiji/airsonic-advanced/blob/d7b8ff6ac8284701af801b6c0c9753d173c3486b/airsonic-main/src/main/java/org/airsonic/player/service/SecurityService.java#L574-L584
Before [11.1.4-SNAPSHOT.20240613153447](https://github.com/kagemomiji/airsonic-advanced/releases/tag/11.1.4-SNAPSHOT.20240613153447), it is created for external player to access resource in Airsonic Advanced.
After that release, it is also created for access artist image. That is why `guest` user appears frequently.

I don't think there is a high risk of passwords being leaked and causing problems immediately.
But, I agree that automatically generating a guest user and operating in this manner is not ideal. I would like to revise the implementation.

Thank you
