### ISSUE TITLE
[Bug]: latest version not working

### ISSUE THREAD

**Issue by ristein** [kagemomiji/airsonic-advanced#548]
### What happened?

watchtower pulled a new version tonight called 3d5ce2eec33f but I can't connect to it as before.
Browser says unable to connect.
Docker inspect says following:
"Health": {
                "Status": "unhealthy",
                "FailingStreak": 13,
                "Log": [
                    {
                        "Start": "2024-07-21T09:38:14.329475629+02:00",
                        "End": "2024-07-21T09:38:14.404532378+02:00",
                        "ExitCode": 1,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\ncurl: (7) Failed to connect to localhost port 4040 after 0 ms: Connection refused\n"
                    },

### Steps to reproduce

not sure how to reproduce.
if any log needed please ask

### Version

11.1.4-SNAPSHOT (Edge)

### Version Detail

"Image": "sha256:3d5ce2eec33f0398c4f52d3d01e96c8453232d77c3118226ccdc8908d0fbe49c",

### Operating System

Ubuntu 22, docker

### Java Version

docker

### Database

Other

### Configuration paramter

docker run -it --name=airsonic-kagemomiji -e PUID=1007 -e PGID=1001 -e TZ=Europe/Berlin -p 14040:4040 -v /data/airsonic-kagemomiji/config:/config -v /mnt/TOSHI1/use/music/:/music_use -v /mnt/TOSHI1/yt-dlp/music/:/music_yt -v /data/airsonic-kagemomiji/playlists:/playlists -v /data/airsonic-kagemomiji/podcasts:/podcasts --device /dev/snd:/dev/snd --restart unless-stopped ghcr.io/kagemomiji/airsonic-advanced:latest

### Proxy Server

apache2

### client detail

firefox

### language

None

**Comment by kagemomiji** [comment]
@ristein 
Could you share me the log of the docker container?
`docker logs airsonic-kagemomiji`

**Comment by ristein** [comment]
[log.txt](https://github.com/user-attachments/files/16325277/log.txt)

**Comment by hiyadragon** [comment]
[_airsonic-advanced_logs(1).txt](https://github.com/user-attachments/files/16326471/_airsonic-advanced_logs.1.txt)
 same issue

**Comment by kagemomiji** [comment]
@hiyadragon @ristein 
I have created fixed image. Could you try?
ghcr.io/kagemomiji/airsonic-advanced:pr-549
[war file in zip](https://github.com/kagemomiji/airsonic-advanced/actions/runs/10042841049/artifacts/1726368550)

**Comment by ristein** [comment]
sorry, I'm on vacation now 😐

**Comment by hiyadragon** [comment]
> @hiyadragon @ristein I have created fixed image. Could you try? ghcr.io/kagemomiji/airsonic-advanced:pr-549 [war file in zip](https://github.com/kagemomiji/airsonic-advanced/actions/runs/10042841049/artifacts/1726368550)

pr-549 is working properly .. Thank you for the time and effort keeping this great project alive!!!!!
