### ISSUE TITLE
[Bug]: Translation bug: Recently Played 

### ISSUE THREAD

**Issue by bartmans** [kagemomiji/airsonic-advanced#586]
### What happened?

The heading on the righthand side of the screen is not translated in Dutch. It says 'Recently Played' it should be 'Net afgespeeld'

### Steps to reproduce

The heading on the righthand side of the screen is not translated in Dutch. It says 'Recently Played' it should be 'Net afgespeeld'

### Version

11.1.4-SNAPSHOT (Edge)

### Version Detail

 	11.1.4-SNAPSHOT.20240829225404

### Operating System

Synology Docker

### Java Version

Apache Tomcat/9.0.74, java 17.0.5, Linux (1,07 GB / 1,67 GB)

### Database

Other

### DB Detail

sqlite

### Configuration paramter

not applicable

### language

Dutch

**Comment by maghiel** [comment]
Imho a better translation would be "Recent Afgespeeld" or "Recent Geluisterd". "Net" would suggest a few seconds ago, plus it's more spoken language instead of written language.

**Comment by bartmans** [comment]
Both points were what I wanted :-). But 'Recent Geluisterd' is fine.

**Comment by maghiel** [comment]
@bartmans my pull request should fix this, it's up to @kagemomiji to merge it now ;)

**Comment by bartmans** [comment]
Mmm. Latest Edge now shows only the Recently played, not the 'Now playing'.

**Comment by maghiel** [comment]
@bartmans I believe that's a separate issue. 
I've tested it in an older snapshot (11.1.4-SNAPSHOT.20240720124838) and the same issue occurs, also in other languages. To me it appears like _Now Playing_ is shown for a fraction of a second to be replaced with _Recently played_
It's also a separate issue from 381 as the pane is not empty. 
My knowledge of airsonic is far too limited to solve this.
