### ISSUE TITLE
[Bug]: Airsonic encountered an internal issue [on logout]

### ISSUE THREAD

**Issue by AMDphreak** [kagemomiji/airsonic-advanced#590]
### What happened?

![image](https://github.com/user-attachments/assets/3ddbd841-14da-43b0-8475-0ac86f20769f)

> Airsonic encountered an internal error. You can report this error in the GitHub Issue. Please include the information below.
> 
> Back
> Status	403
> Error	Forbidden
> Message	
> Path	/logout
> Time	Wed Sep 11 00:44:31 UTC 2024
> Exception	
> Java version	Eclipse Adoptium 17.0.10
> Operating system	Linux 5.14.0-447.el9.x86_64
> Memory	Used 128 of 175 MB
> Stack trace	
>                 
>             

### Steps to reproduce

1. initialize pod on pikapods
2. attempt to change admin password in settings
3. observe the page doesn't update. refresh page or reopen app in new page
4. go back to users page in settings. observe "page updated" message displayed momentarily
5. click logout button. observe only the "connected" button changed. No page change happened.
6. click the Logout button again. Error message displays in scrollable div above app

I tried 2 passwords because it didn't look like it saved the first time:
1. e8AWTLC8Rg@cHm#m
2. Irritably-Spouse-December6

### Version

11.1.4-SNAPSHOT (Edge)

### Version Detail

edge-11.1.4-SNAPSHOT

### Operating System

Linux 5.14.0-447.el9.x86_64

### Java Version

Eclipse Adoptium 17.0.10

### Database

Other

### DB Detail

don't know

### Configuration paramter

No idea what this is

### language

English (United States)

**Comment by kagemomiji** [comment]
@AMDphreak 
I tried using Pikapod, but it seems that the deployment settings on Pikapod's side are incomplete. It appears that the Docker container is being pulled and started, but the JAVA_OPTS environment variable seems to be missing `-Dserver.forward-headers-strategy=native`.

**Comment by m3nu** [comment]
Hey all, [pikapods.com](https://pikapods.com) founder here. I've added this setting on our site and don't see the mixed content error any more. We can apply this to all existing pods in a few hours.

**Comment by AMDphreak** [comment]
> Hey all, [pikapods.com](https://pikapods.com) founder here. I've added this setting on our site and don't see the mixed content error any more. We can apply this to all existing pods in a few hours.

Nice, thank you. I'm surprised and glad you frequent this forum

**Comment by AMDphreak** [comment]
> Hey all, [pikapods.com](https://pikapods.com) founder here. I've added this setting on our site and don't see the mixed content error any more. We can apply this to all existing pods in a few hours.

Are you hiring? I am in need of a job, and would like to work in software, which I went to school to do, but have not had any luck with job applications.

**Comment by m3nu** [comment]
Not right now. Sorry.
