### ISSUE TITLE
Bump up to 11.0.2

### ISSUE THREAD

**Issue by kagemomiji** [kagemomiji/airsonic-advanced#75]
Bump up release version to 11.0.2

**Comment by masterwishx** [comment]
Thanks for your work, can your version be installed on docker ?

**Comment by kagemomiji** [comment]
@masterwishx 
I released my work to ghcr.
you can pull images from ghcr.io/kagemomiji/airsonic-advanced

**Comment by masterwishx** [comment]
@kagemomiji OK got it
